apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplex-backend-deployment
  labels:
    app: simplex-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplex-backend
  template:
    metadata:
      labels:
        app: simplex-backend
    spec:
      containers:
        - name: simplex-backend
          image: siverteh/simplex-backend:latest  # Ensure this points to your backend image in the container registry
          imagePullPolicy: Always
          ports:
            - containerPort: 5050  # This should match the port your backend listens on
