
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplex-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplex-database
  template:
    metadata:
      labels:
        app: simplex-database
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: simplex-database-secret
                  key: postgres-password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-db-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: simplex-database-pvc
        - name: init-db-script
          configMap:
            name: simplex-database-init
