apiVersion: v1
kind: Service
metadata:
  name: simplex-frontend-service
spec:
  type: NodePort  # Change to LoadBalancer if you're on a cloud provider that supports it
  selector:
    app: simplex-frontend
  ports:
    - port: 8080
      targetPort: 8080  # This should match the container's listening port
