apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplex-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              value: "skallesverd5"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: database-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: simplex-database-pvc
