apiVersion: v1
kind: Service
metadata:
  name: simplex-backend-service
spec:
  type: NodePort  # Change to LoadBalancer if appropriate for your environment
  selector:
    app: simplex-backend
  ports:
    - port: 8080
      targetPort: 8080  # This should match the container's listening port

