apiVersion: v1
kind: ConfigMap
metadata:
  name: simplex-database-init
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS "pgcrypto";

    CREATE TABLE IF NOT EXISTS "AspNetUsers" (
        "Id" TEXT PRIMARY KEY,
        "UserName" VARCHAR(256) NOT NULL,
        "NormalizedUserName" VARCHAR(256) NOT NULL UNIQUE,
        "Email" VARCHAR(256),
        "NormalizedEmail" VARCHAR(256) UNIQUE,
        "EmailConfirmed" BOOLEAN NOT NULL,
        "PasswordHash" TEXT,
        "SecurityStamp" TEXT,
        "ConcurrencyStamp" TEXT,
        "PhoneNumber" TEXT,
        "PhoneNumberConfirmed" BOOLEAN NOT NULL,
        "TwoFactorEnabled" BOOLEAN NOT NULL,
        "LockoutEnd" TIMESTAMPTZ,
        "LockoutEnabled" BOOLEAN NOT NULL,
        "AccessFailedCount" INT NOT NULL
        );

    CREATE TABLE IF NOT EXISTS "Projects" (
        "ProjectId" TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
        "Title" VARCHAR(256) NOT NULL,
        "Owner" VARCHAR(256) NOT NULL,
        "LatexCode" TEXT,
        "WorkspaceState" TEXT,
        "CreationDate" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "LastModifiedDate" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "UserId" TEXT NOT NULL,
        FOREIGN KEY ("UserId") REFERE
    NCES "AspNetUsers"("Id") ON DELETE CASCADE
    );