apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplex-compiler-deployment
spec:
  replicas: 1  # Start with 1 replica, can be scaled as needed
  selector:
    matchLabels:
      app: simplex-compiler
  template:
    metadata:
      labels:
        app: simplex-compiler
    spec:
      containers:
        - name: simplex-compiler
          image: siverteh/simplex-compiler:latest
          ports:
            - containerPort: 8080  # Ensure this matches the port your app listens on
